### ISSUE TITLE
Balgruuf Doesn't Give the Thane Weapon.

### ISSUE THREAD

**Issue by AronaxAE** [ForgottenGlory/Living-Skyrim-2#294]
**LS Version**
2.0.2

**Describe the bug**
Went back to Dragonsreach after beating the dragon at the watch tower. Spoke to him and everything was fine, I got the Thane title correctly, but when he ends the conversation and tells you he is giving you the weapon, it simply doesn't enter your inventory or even prompt that it got given to you.

**To Reproduce**
I have no idea how to reproduce this unless you play through until this point, but other people have apparently had this same issue and had to console the weapon in.

**Expected behavior**
The thane weapon should be given to the player after dialogue with Balgruuf ends.

**Screenshots**
Not really anything to screenshot.

**Comment by ForgottenGlory** [comment]
Everything I can see looks correct regarding the quest rewards... I'm open to suggestions on how to fix this.

**Comment by jtmoney412** [comment]
I had the same problem again on the most recent LS update. I can try reloading before going into Dragonsreach and seeing if I get the weapon this time. Let me know if there's any other testing I can do or ways to help.

**Comment by TwistedModding** [comment]
https://www.nexusmods.com/skyrimspecialedition/mods/11802?tab=posts

thane weapon bug from dbm
creator stickied a post on it
and the fix is in the files tab
https://www.nexusmods.com/skyrimspecialedition/mods/11802?tab=files

 Thane weapon delivery script fix
Nexus Mods :: Skyrim Special Edition
Legacy of the Dragonborn SSE
Legacy of the Dragonborn will forever change how you play Skyrim. Not just a display mod, not just a quest mod, not just a new guild mod, but a complete foundational flagship mod to build an entire lo

https://discordapp.com/channels/605449136870916175/688593507966779453/752380794621657249 this guy found it.

he just said he couldnt get the fix to work, but it might still be worth a try cause i highly doubt he tried it on a new save.

**Comment by ForgottenGlory** [comment]
Fixed 2.4.0
