### ISSUE TITLE
CTD on ASLAL Alik'r Start

### ISSUE THREAD

**Issue by SlyFoxer** [ForgottenGlory/Living-Skyrim-2#361]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

[Crash_2020_8_3_14-17-5.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5017623/Crash_2020_8_3_14-17-5.txt)

If possible, please also attach a copy of your most recent save before the issue occurred.**

[Save5_D7E5CB2A_0_4461766964_AbandonedPrison01_000031_20200803181649_1_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5017632/Save5_D7E5CB2A_0_4461766964_AbandonedPrison01_000031_20200803181649_1_1.zip)

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.2.0

**Describe the bug**
The game CTDs after using the bed after selecting the Alik'r start in ASLAL.

**To Reproduce**
1. Make a Redguard character
2. Use the Mara statue and select the Alik'r start
3. Use the bed
4. The game CTDs during the loading screen

**Expected behavior**
The game to start me as an Alik'r without crashing

**Comment by TwistedModding** [comment]
this is a memory error.
Follow these instructions and close the post.

Bigger Skyrim modlists need a lot of memory, and when there is not enough available it may fail allocating more. To fix this, you'll want to have a bigger pagefile.

A pagefile is a file on your disk Windows will use when there is not enough RAM available.

Never disable the pagefile - this may lead to various issues on your system, such as this Skyrim crash.

If you've never touched the pagefile, try performing the following steps:
1. Press Windows + R on your keyboard and enter sysdm.cpl ,3
2. Under the Performance section, press 'Settings'
3. Go to the Advanced tab at the top, and at the Virtual memory section press 'Change...'
4. Disable 'Automatically manage paging file size for all drives'
5. If you have more than one drive, try enabling it for at least one more drive as a backup (make sure it has a decent bit of free space, like 15GB). Set the size to 'System managed size'.
Otherwise, set a custom size for the drive it's currently on and increase the maximum size to be at least 20GB.
