### ISSUE TITLE
Randomly CTD 

### ISSUE THREAD

**Issue by alexjoe9** [ForgottenGlory/Living-Skyrim-2#427]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

After a decent time playing and ensuring everything set up correctly I get crashes to desktop. Usually on some kind of transition. the lastest one was travelling between riverwood and Whiterun. just defeated the gian and was about to walkthrough the "road Block" if I stay in one area for awhile it seems to be fine but any kind of travel or transition I have experienced CTD pretty often. with or without ENB. 
[Crash_2020_9_6_23-20-40.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5181497/Crash_2020_9_6_23-20-40.txt)

**Comment by TwistedModding** [comment]
This crash is due to your pagefile. Follow these steps then close the bug report.

Bigger Skyrim modlists need a lot of memory, and when there is not enough available it may fail allocating more. To fix this, you'll want to have a bigger pagefile.

A pagefile is a file on your disk Windows will use when there is not enough RAM available.

Never disable the pagefile - this may lead to various issues on your system, such as this Skyrim crash.

If you've never touched the pagefile, try performing the following steps:
1. Press Windows + R on your keyboard and enter sysdm.cpl ,3
2. Under the Performance section, press 'Settings'
3. Go to the Advanced tab at the top, and at the Virtual memory section press 'Change...'
4. Disable 'Automatically manage paging file size for all drives'
5. If you have more than one drive, try enabling it for at least one more drive as a backup (make sure it has a decent bit of free space, like 15GB). Set the size to 'System managed size'.
Otherwise, set a custom size for the drive it's currently on and increase the maximum size to be at least 20GB.
