### ISSUE TITLE
CTD when fast traveling/carriage travel, and when going through doors, especially around/in cities

### ISSUE THREAD

**Issue by crkilg4z** [ForgottenGlory/Living-Skyrim-2#454]
[Crash_2020_9_27_18-58-30.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5295417/Crash_2020_9_27_18-58-30.txt)
[Crash_2020_9_27_19-24-47.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5295418/Crash_2020_9_27_19-24-47.txt)
[Crash_2020_9_27_21-29-6.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5295419/Crash_2020_9_27_21-29-6.txt)
[Crash_2020_9_28_18-35-54.txt](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5295420/Crash_2020_9_28_18-35-54.txt)

If possible, please also attach a copy of your most recent save before the issue occurred.**

[Save file for report.zip](https://github.com/ForgottenGlory/Living-Skyrim-2/files/5295469/Save.file.for.report.zip)

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**

Version 2

**Describe the bug**

Almost every time I attempt to fast travel anywhere, or use the carriage services, my game will crash while on the load screen.  Also when I am going through doors, especially inside of cities, same problem, crashing on load screen.  The game will also crash at times when I am approaching a city, such as Whiterun just before I get to the stables.

**To Reproduce**

Fast travel, use carriage, attempt to enter/exit shops and homes inside cities, walk around the exterior of major cities.

**Expected behavior**

To be able to fast travel and enter/exit buildings without CTD.

**Screenshots**
If applicable, add screenshots to help explain your problem. **IF YOUR SCREENSHOT CONTAINS NUDITY DO NOT PUT IT ON GITHUB.** Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by TwistedModding** [comment]
Bigger Skyrim modlists need a lot of memory, and when there is not enough available it may fail allocating more. To fix this, you'll want to have a bigger pagefile.

A pagefile is a file on your disk Windows will use when there is not enough RAM available.

Never disable the pagefile - this may lead to various issues on your system, such as this Skyrim crash.

If you've never touched the pagefile, try performing the following steps:
1. Press Windows + R on your keyboard and enter sysdm.cpl ,3
2. Under the Performance section, press 'Settings'
3. Go to the Advanced tab at the top, and at the Virtual memory section press 'Change...'
4. Disable 'Automatically manage paging file size for all drives'
5. If you have more than one drive, try enabling it for at least one more drive as a backup (make sure it has a decent bit of free space, like 15GB). Set the size to 'System managed size'.
Otherwise, set a custom size for the drive it's currently on and increase the maximum size to be at least 20GB.

Follow these steps and close this github report. Its a memory crash.

**Comment by crkilg4z** [comment]
I formatted an external hard drive and set it and the drive I have steam installed on to system managed size like you said.  The crashing has stopped but now I am having horrible lag almost constantly if I'm anywhere near civilization, and still consistent lag out in the wilderness and inside dungeons.

**Comment by SpookyAzizi** [comment]
im having the same issue kinda, even tho i know my memory is all in check.

**Comment by ForgottenGlory** [comment]
The crash logs are saying it's a memory issue. Follow the page file steps.
